Date: Wed, 11 Apr 1990  01:36 MDT
From: Keith Petersen <w8sdz@WSMR-SIMTEL20.ARMY.MIL>
To: David Kirschbaum <kirsch@usasoc.soc.mil>
Cc: Info-ZIP@WSMR-SIMTEL20.ARMY.MIL
Subject: Release of unzip for Unix

> I've been waiting to see if there were any new changes/improvements, but
> nothing lately.  I guess there ARE still some systems the latest won't run
> on .. but nobody's fixing it.  So be it.

Please put a note in the release, telling how to contact Info-ZIP to
report bugs/improvements/additional ports.  The uucp address most
useful to Usenet people would be:  uunet!wsmr-simtel20.army.mil!info-zip

> (And I've been good too .. didn't stick in ONE "Toad" ANYWHERE!)

Anyone who knows about the world famous Toad Hall source of programs
will know what a sacrifice you've made.  Thanks!   :-)

--Keith

(And back at Toad Hall .. that "world famous" bit is an inside joke,
guys .. we're just kidding .. really!

So .. to contact Info-ZIP for reporting bugs/improvements/additional ports:
  Usenet people via uucp:  uunet!wsmr-simtel20.army.mil!info-zip
  ARPAnet:		   Info-ZIP@wsmr-simtel20.army.mil

David Kirschbaum
moderator?
13 Apr 90

22 May 90:  Keith is moving Info-ZIP to another host, so the above addresses
will be:
  Usenet people via uucp:  uunet!tacom-emh1.army.mil!info-zip
  ARPAnet:		   Info-ZIP@tacom-emh1.army.mil

25 May 90:  Informed yet again by Keith that (because he's also losing access
to tacom-emh1) Info-ZIP will return to wsmr-simtel20.army.mil
so .. back to the original addresses, folks.

